package usr.sample.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-02-27T14:56:21.097+04:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "SampleService_HttpService", 
                  wsdlLocation = "file:/D:/TCS/project/SampleProject/src/main/resources/wsdl/SampleService.wsdl",
                  targetNamespace = "http://ws.sample.usr") 
public class SampleServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.sample.usr", "SampleService_HttpService");
    public final static QName SampleServiceHttpPort = new QName("http://ws.sample.usr", "SampleService_HttpPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TCS/project/SampleProject/src/main/resources/wsdl/SampleService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SampleServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/TCS/project/SampleProject/src/main/resources/wsdl/SampleService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SampleServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SampleServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SampleServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SampleServiceHttpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SampleServiceHttpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SampleServiceHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SampleService
     */
    @WebEndpoint(name = "SampleService_HttpPort")
    public SampleService getSampleServiceHttpPort() {
        return super.getPort(SampleServiceHttpPort, SampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleService
     */
    @WebEndpoint(name = "SampleService_HttpPort")
    public SampleService getSampleServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(SampleServiceHttpPort, SampleService.class, features);
    }

}
