package usr.sample.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-12-20T16:24:36.024+04:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://ws.sample.usr", name = "SampleService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SampleService {

    @WebMethod(action = "http://sample.usr")
    @WebResult(name = "result", targetNamespace = "", partName = "result")
    public java.lang.String getStr1(
        @WebParam(partName = "yourName", name = "yourName", targetNamespace = "")
        java.lang.String yourName
    );
}
